---
- name: Basic System Setup - Ubuntu
  hosts: web
  become: true
  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        name: '*'
        update_cache: true
        cache_valid_time: 3600
    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist
        
    - name: Create a new user
      ansible.builtin.user:
        name: Lahiru
        state: present
        create_home: true